spring:
  application:
    name: yunnan-city
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yunnan_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  druid:
    url: jdbc:avatica:remote:url=http://localhost:8888/druid/v2/sql/avatica/
    driver-class-name: org.apache.calcite.avatica.remote.Driver
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 2000

project:
  folder: D:\\STUDY\\beijing_universiti_folder7\\excellent_engineering_code\\yunnan\\

log:
  root:
    level: DEBUG

server:
  port: 8081
  servlet:
    context-path: /api
